name: 'Setup Ebitengine'
description: 'Setup environment for Ebitengine development on Ubuntu'
author: 'nao1215'
inputs: {}
runs:
  using: 'composite'
  steps:
    - name: Install dependencies on Ubuntu
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y gcc libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
